global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'notifications'

receivers:
  - name: 'notifications'
    slack_configs:
      - channel: '#alex_eshenko'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
