version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui
    ports:
      - ${UI_PORT:-9292}:9292/tcp
    networks:
      - front_net
    depends_on:
      - post
      - comment

  post:
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db

  comment:
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: ${BACK_NET:-10.0.2.0/24}
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_NET:-10.0.1.0/24}
