version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build:
      context: ./ui
      dockerfile: ${UI_DOCKERFILE:-Dockerfile}
    image: ${USERNAME}/ui:${UI_VERSION:-1.0}
    ports:
      - ${UI_PORT:-9292}:9292/tcp
    networks:
      - front_net
    depends_on:
      - post
      - comment

  post:
    build:
      context: ./post-py
      dockerfile: ${POST_DOCKERFILE:-Dockerfile}
    image: ${USERNAME}/post:${POST_VERSION:-1.0}
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db

  comment:
    build:
      context: ./comment
      dockerfile: ${COMMENT_DOCKERFILE:-Dockerfile}
    image: ${USERNAME}/comment:${COMMENT_VERSION:-1.0}
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: ${BACK_NET:-10.0.2.0/24}
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_NET:-10.0.1.0/24}
